### ISSUE TITLE
Check name should be configurable with a default rather than static

### ISSUE THREAD

**Issue by allout58** [jenkinsci/checks-api-plugin#27]
The Check Name is currently static. It would be very nice to be able to configure this, possibly with the current value of `Jenkins` as a default.

See: https://github.com/jenkinsci/checks-api-plugin/blob/0ee3cec8fe745d1ab5e21f59a1681d09a95a08c5/src/main/java/io/jenkins/plugins/checks/BuildStatusChecksPublisher.java#L36

**Comment by XiongKezhi** [comment]
Thanks, that's a good point.

We'll try to add that feature alone with the disability for publishing such automatic status checks

**Comment by medianick** [comment]
Yes, and since this works as an alternative to the historic `continuous-integration/jenkins/pr-merge`, `continuous-integration/jenkins/branch`, etc. commit statuses, it would also be valuable to have the default check name be more like these values (e.g., "PR Merge Build" or "Branch Build") rather than just "Jenkins". A generic name like "Jenkins" doesn't make a lot of sense alongside other more specific checks published (like "Code Coverage" or anything from Warnings NG, like "MSBuild"):

![image](https://user-images.githubusercontent.com/329902/93638347-1f773100-f9c5-11ea-8306-ab4600bdf4e8.png)
