### ISSUE TITLE
Question: deterministic order of `ChecksPublisherFactory` execution

### ISSUE THREAD

**Issue by agaudreault-jive** [jenkinsci/checks-api-plugin#71]
I am not sure if this will cause us a problem, but I'll ask in advance!

We are in the process of creating a custom extension of `ChecksPublisherFactory`, because the ones in the github-checks-plugin does not satisfy our usecase, even if we use github. We have GitSCM configured to checkout the Jenkinsfile from a repository, but we do not want to send the checks to that same repository. I see that the code below for the factory only takes the first valid publisher it finds. I was wondering what will happen if the two factories return a publisher. 

Can we guarantee the order of the factories to make sure ours will be executed first ?

https://github.com/jenkinsci/checks-api-plugin/blob/c83076d7dc39a83095519378c3a9a1631f057832/src/main/java/io/jenkins/plugins/checks/api/ChecksPublisherFactory.java#L96-L105

**Comment by XiongKezhi** [comment]
yes, that's a problem since we didn't expect there will be such a use case; we thought users will always use our implementation for GitSCM or GitHub Branch Source SCM (they are exclusive so the order is fine).

Now maybe making the `ChecksPublisher` comparable so that we can sort the stream before `findFirst` will solve the problem. We can make our implementation the lowest priority and the users' will be used first.

**Comment by timja** [comment]
or making it user selectable and hiding the choice if only one extension is available?
it's a reasonably common pattern,

Used in at least github api endpoints, fingerprinting, junit pluggable storage

**Comment by uhafner** [comment]
I think I have the same problem in my git-forensics plugin that tries to select reference builds (and mines repositories). It would make sense if we could use the same approach. The same happens if someone checks out from several repositories: I think we should make it possible to configure the repository (and use the first one if nothing has been configured). See https://github.com/jenkinsci/git-forensics-plugin/pull/213

**Comment by KalleOlaviNiemitalo** [comment]
> Can we guarantee the order of the factories to make sure ours will be executed first ?

You could specify a high [ordinal](https://javadoc.jenkins.io/hudson/Extension.html#ordinal--), e.g. `@Extension(ordinal = 100000)`. I think that would let your factory be called first, especially if other implementations don't specify ordinals at all.

**Comment by agaudreault-jive** [comment]
Thanks @KalleOlaviNiemitalo, I looked at the doc too quickly and never saw ordinal there! It seems like it will solve my usecase.

https://github.com/jenkinsci/jenkins/blob/master/test/src/test/java/hudson/ExtensionListTest.java#L199-L208
